// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Math.proto

#ifndef PROTOBUF_Math_2eproto__INCLUDED
#define PROTOBUF_Math_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Math_2eproto();
void protobuf_AssignDesc_Math_2eproto();
void protobuf_ShutdownFile_Math_2eproto();

class PB_Vector2i;
class PB_Vector3f;
class PB_Vector4f;

// ===================================================================

class PB_Vector2i : public ::google::protobuf::Message {
 public:
  PB_Vector2i();
  virtual ~PB_Vector2i();
  
  PB_Vector2i(const PB_Vector2i& from);
  
  inline PB_Vector2i& operator=(const PB_Vector2i& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_Vector2i& default_instance();
  
  void Swap(PB_Vector2i* other);
  
  // implements Message ----------------------------------------------
  
  PB_Vector2i* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_Vector2i& from);
  void MergeFrom(const PB_Vector2i& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);
  
  // optional int32 y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:PB_Vector2i)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_Math_2eproto();
  friend void protobuf_AssignDesc_Math_2eproto();
  friend void protobuf_ShutdownFile_Math_2eproto();
  
  void InitAsDefaultInstance();
  static PB_Vector2i* default_instance_;
};
// -------------------------------------------------------------------

class PB_Vector3f : public ::google::protobuf::Message {
 public:
  PB_Vector3f();
  virtual ~PB_Vector3f();
  
  PB_Vector3f(const PB_Vector3f& from);
  
  inline PB_Vector3f& operator=(const PB_Vector3f& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_Vector3f& default_instance();
  
  void Swap(PB_Vector3f* other);
  
  // implements Message ----------------------------------------------
  
  PB_Vector3f* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_Vector3f& from);
  void MergeFrom(const PB_Vector3f& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);
  
  // optional float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);
  
  // optional float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);
  
  // @@protoc_insertion_point(class_scope:PB_Vector3f)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float x_;
  float y_;
  float z_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_Math_2eproto();
  friend void protobuf_AssignDesc_Math_2eproto();
  friend void protobuf_ShutdownFile_Math_2eproto();
  
  void InitAsDefaultInstance();
  static PB_Vector3f* default_instance_;
};
// -------------------------------------------------------------------

class PB_Vector4f : public ::google::protobuf::Message {
 public:
  PB_Vector4f();
  virtual ~PB_Vector4f();
  
  PB_Vector4f(const PB_Vector4f& from);
  
  inline PB_Vector4f& operator=(const PB_Vector4f& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_Vector4f& default_instance();
  
  void Swap(PB_Vector4f* other);
  
  // implements Message ----------------------------------------------
  
  PB_Vector4f* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_Vector4f& from);
  void MergeFrom(const PB_Vector4f& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);
  
  // optional float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);
  
  // optional float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);
  
  // optional float w = 4;
  inline bool has_w() const;
  inline void clear_w();
  static const int kWFieldNumber = 4;
  inline float w() const;
  inline void set_w(float value);
  
  // @@protoc_insertion_point(class_scope:PB_Vector4f)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_w();
  inline void clear_has_w();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float x_;
  float y_;
  float z_;
  float w_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_Math_2eproto();
  friend void protobuf_AssignDesc_Math_2eproto();
  friend void protobuf_ShutdownFile_Math_2eproto();
  
  void InitAsDefaultInstance();
  static PB_Vector4f* default_instance_;
};
// ===================================================================


// ===================================================================

// PB_Vector2i

// optional int32 x = 1;
inline bool PB_Vector2i::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_Vector2i::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_Vector2i::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_Vector2i::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 PB_Vector2i::x() const {
  return x_;
}
inline void PB_Vector2i::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
}

// optional int32 y = 2;
inline bool PB_Vector2i::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PB_Vector2i::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PB_Vector2i::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PB_Vector2i::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 PB_Vector2i::y() const {
  return y_;
}
inline void PB_Vector2i::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// PB_Vector3f

// optional float x = 1;
inline bool PB_Vector3f::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_Vector3f::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_Vector3f::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_Vector3f::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float PB_Vector3f::x() const {
  return x_;
}
inline void PB_Vector3f::set_x(float value) {
  set_has_x();
  x_ = value;
}

// optional float y = 2;
inline bool PB_Vector3f::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PB_Vector3f::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PB_Vector3f::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PB_Vector3f::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float PB_Vector3f::y() const {
  return y_;
}
inline void PB_Vector3f::set_y(float value) {
  set_has_y();
  y_ = value;
}

// optional float z = 3;
inline bool PB_Vector3f::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PB_Vector3f::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PB_Vector3f::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PB_Vector3f::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float PB_Vector3f::z() const {
  return z_;
}
inline void PB_Vector3f::set_z(float value) {
  set_has_z();
  z_ = value;
}

// -------------------------------------------------------------------

// PB_Vector4f

// optional float x = 1;
inline bool PB_Vector4f::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_Vector4f::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_Vector4f::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_Vector4f::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float PB_Vector4f::x() const {
  return x_;
}
inline void PB_Vector4f::set_x(float value) {
  set_has_x();
  x_ = value;
}

// optional float y = 2;
inline bool PB_Vector4f::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PB_Vector4f::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PB_Vector4f::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PB_Vector4f::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float PB_Vector4f::y() const {
  return y_;
}
inline void PB_Vector4f::set_y(float value) {
  set_has_y();
  y_ = value;
}

// optional float z = 3;
inline bool PB_Vector4f::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PB_Vector4f::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PB_Vector4f::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PB_Vector4f::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float PB_Vector4f::z() const {
  return z_;
}
inline void PB_Vector4f::set_z(float value) {
  set_has_z();
  z_ = value;
}

// optional float w = 4;
inline bool PB_Vector4f::has_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PB_Vector4f::set_has_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PB_Vector4f::clear_has_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PB_Vector4f::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline float PB_Vector4f::w() const {
  return w_;
}
inline void PB_Vector4f::set_w(float value) {
  set_has_w();
  w_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Math_2eproto__INCLUDED
